# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'param_settings_v3.ui'
#
# Created: Tue Dec 23 11:37:49 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class MyListWidget(QtGui.QListWidget):
    def __init__(self, parent=None):
        super(MyListWidget, self).__init__(parent)
        self.itemClicked.connect(self.on_item_clicked)

    def mousePressEvent(self, event):
        self._mouse_button = event.button()
        super(MyListWidget, self).mousePressEvent(event)

    def on_item_clicked(self):
        return self._mouse_button

class Ui_form(object):
    def setupUi(self, form):
        form.setObjectName(_fromUtf8("form"))
        form.resize(826, 625)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        form.setFont(font)
        self.frame_2 = QtGui.QFrame(form)
        self.frame_2.setGeometry(QtCore.QRect(20, 30, 811, 161))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.frame = QtGui.QFrame(self.frame_2)
        self.frame.setGeometry(QtCore.QRect(150, 20, 651, 131))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(28)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.layoutWidget = QtGui.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 151, 26))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_min_wavelen = QtGui.QLabel(self.layoutWidget)
        self.label_min_wavelen.setStatusTip(_fromUtf8(""))
        self.label_min_wavelen.setWhatsThis(_fromUtf8(""))
        self.label_min_wavelen.setObjectName(_fromUtf8("label_min_wavelen"))
        self.label_min_wavelen.setToolTip("minimum wavelength of Gabor filter, in number of pixels\nDefault = 5")
        self.horizontalLayout_7.addWidget(self.label_min_wavelen)
        self.spinBox_min_wavelen = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_min_wavelen.setMaximumSize(QtCore.QSize(55, 16777215))
        self.spinBox_min_wavelen.setToolTip(_fromUtf8(""))
        self.spinBox_min_wavelen.setWhatsThis(_fromUtf8(""))
        self.spinBox_min_wavelen.setMaximum(9999)
        self.spinBox_min_wavelen.setObjectName(_fromUtf8("spinBox_min_wavelen"))
        self.horizontalLayout_7.addWidget(self.spinBox_min_wavelen)
        self.layoutWidget1 = QtGui.QWidget(self.frame)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 50, 151, 26))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_max_wavelen = QtGui.QLabel(self.layoutWidget1)
        self.label_max_wavelen.setToolTip("maximum wavelength of Gabor filter, in number of pixels\nDefault = 40")
        self.label_max_wavelen.setObjectName(_fromUtf8("label_max_wavelen"))
        self.horizontalLayout_6.addWidget(self.label_max_wavelen)
        self.spinBox_max_wavelen = QtGui.QSpinBox(self.layoutWidget1)
        self.spinBox_max_wavelen.setMaximumSize(QtCore.QSize(55, 16777215))
        self.spinBox_max_wavelen.setMaximum(9999)
        self.spinBox_max_wavelen.setObjectName(_fromUtf8("spinBox_max_wavelen"))
        self.horizontalLayout_6.addWidget(self.spinBox_max_wavelen)
        self.layoutWidget2 = QtGui.QWidget(self.frame)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 90, 151, 26))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_freq_step = QtGui.QLabel(self.layoutWidget2)
        self.label_freq_step.setObjectName(_fromUtf8("label_freq_step"))
        self.label_freq_step.setToolTip("multipy factor to the next frequency\nDefault = 2")
        self.horizontalLayout_5.addWidget(self.label_freq_step)
        self.spinBox_freq_step = QtGui.QSpinBox(self.layoutWidget2)
        self.spinBox_freq_step.setMaximumSize(QtCore.QSize(55, 16777215))
        self.spinBox_freq_step.setMaximum(9999)
        self.spinBox_freq_step.setObjectName(_fromUtf8("spinBox_freq_step"))
        self.horizontalLayout_5.addWidget(self.spinBox_freq_step)
        self.layoutWidget3 = QtGui.QWidget(self.frame)
        self.layoutWidget3.setGeometry(QtCore.QRect(190, 10, 151, 26))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_bandwidth = QtGui.QLabel(self.layoutWidget3)
        self.label_bandwidth.setObjectName(_fromUtf8("label_bandwidth"))
        self.label_bandwidth.setToolTip("wavelength/std-of-Gaussian, doubling the value corresponds to \nhalving the size of the Gaussian kernel in each dimension \n(kernel is always spherical)\nDefault = 1.0 3/2 wavelengths within the window")
        self.horizontalLayout_3.addWidget(self.label_bandwidth)
        self.spinBox_bandwidth = QtGui.QDoubleSpinBox(self.layoutWidget3)
        self.spinBox_bandwidth.setMaximumSize(QtCore.QSize(55, 16777215))
        self.spinBox_bandwidth.setMaximum(9999.99)
        self.spinBox_bandwidth.setObjectName(_fromUtf8("spinBox_bandwidth"))
        self.horizontalLayout_3.addWidget(self.spinBox_bandwidth)
        self.layoutWidget4 = QtGui.QWidget(self.frame)
        self.layoutWidget4.setGeometry(QtCore.QRect(190, 50, 151, 26))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_theta_interval = QtGui.QLabel(self.layoutWidget4)
        self.label_theta_interval.setObjectName(_fromUtf8("label_theta_interval"))
        self.label_theta_interval.setToolTip("interval of Gabor filter orientations, in degrees\nDefault = 15")
        self.horizontalLayout_4.addWidget(self.label_theta_interval)
        self.spinBox_theta_interval = QtGui.QSpinBox(self.layoutWidget4)
        self.spinBox_theta_interval.setMaximumSize(QtCore.QSize(55, 16777215))
        self.spinBox_theta_interval.setMaximum(9999)
        self.spinBox_theta_interval.setObjectName(_fromUtf8("spinBox_theta_interval"))
        self.horizontalLayout_4.addWidget(self.spinBox_theta_interval)
        self.layoutWidget_2 = QtGui.QWidget(self.frame)
        self.layoutWidget_2.setGeometry(QtCore.QRect(380, 50, 251, 63))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_gabor_param_id = QtGui.QLabel(self.layoutWidget_2)
        self.label_gabor_param_id.setObjectName(_fromUtf8("label_gabor_param_id"))
        self.horizontalLayout_9.addWidget(self.label_gabor_param_id)
        self.name_gabor = QtGui.QLineEdit(self.layoutWidget_2)
        self.name_gabor.setObjectName(_fromUtf8("name_gabor"))
        self.horizontalLayout_9.addWidget(self.name_gabor)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.save_gabor = QtGui.QPushButton(self.layoutWidget_2)
        self.save_gabor.setWhatsThis(_fromUtf8(""))
        self.save_gabor.setObjectName(_fromUtf8("save_gabor"))
        self.horizontalLayout_10.addWidget(self.save_gabor)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.layoutWidget5 = QtGui.QWidget(self.frame_2)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 30, 121, 102))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_list_gabor = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_list_gabor.setFont(font)
        self.label_list_gabor.setTextFormat(QtCore.Qt.AutoText)
        self.label_list_gabor.setObjectName(_fromUtf8("label_list_gabor"))
        self.verticalLayout_4.addWidget(self.label_list_gabor)
        self.list_gabor = MyListWidget(self.layoutWidget5)
        self.list_gabor.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.list_gabor.setFrameShape(QtGui.QFrame.WinPanel)
        self.list_gabor.setEditTriggers(QtGui.QAbstractItemView.SelectedClicked)
        self.list_gabor.setProperty("showDropIndicator", False)
        self.list_gabor.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.list_gabor.setObjectName(_fromUtf8("list_gabor"))
        self.verticalLayout_4.addWidget(self.list_gabor)
        self.frame_3 = QtGui.QFrame(form)
        self.frame_3.setGeometry(QtCore.QRect(20, 210, 811, 161))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.frame_4 = QtGui.QFrame(self.frame_3)
        self.frame_4.setGeometry(QtCore.QRect(150, 20, 651, 131))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setLineWidth(28)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.layoutWidget6 = QtGui.QWidget(self.frame_4)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 10, 151, 26))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_n_superpixels = QtGui.QLabel(self.layoutWidget6)
        self.label_n_superpixels.setObjectName(_fromUtf8("label_n_superpixels"))
        self.label_n_superpixels.setToolTip("desired number of superpixels in the over-segmentation\nDefault = 100")
        self.horizontalLayout_8.addWidget(self.label_n_superpixels)
        self.spinBox_n_superpixels = QtGui.QSpinBox(self.layoutWidget6)
        self.spinBox_n_superpixels.setMaximumSize(QtCore.QSize(55, 24))
        self.spinBox_n_superpixels.setMaximum(9999)
        self.spinBox_n_superpixels.setObjectName(_fromUtf8("spinBox_n_superpixels"))
        self.horizontalLayout_8.addWidget(self.spinBox_n_superpixels)
        self.layoutWidget_3 = QtGui.QWidget(self.frame_4)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 50, 156, 26))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_slic_compactness = QtGui.QLabel(self.layoutWidget_3)
        self.label_slic_compactness.setObjectName(_fromUtf8("label_slic_compactness"))
        self.label_slic_compactness.setToolTip("larger value leads to superpixels that are more square\nDefault = 5")
        self.horizontalLayout_11.addWidget(self.label_slic_compactness)
        self.spinBox_slic_compactness = QtGui.QSpinBox(self.layoutWidget_3)
        self.spinBox_slic_compactness.setBaseSize(QtCore.QSize(3, 5))
        self.spinBox_slic_compactness.setMaximum(9999)
        self.spinBox_slic_compactness.setObjectName(_fromUtf8("spinBox_slic_compactness"))
        self.horizontalLayout_11.addWidget(self.spinBox_slic_compactness)
        self.layoutWidget_4 = QtGui.QWidget(self.frame_4)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 90, 151, 26))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_slic_sigma = QtGui.QLabel(self.layoutWidget_4)
        self.label_slic_sigma.setObjectName(_fromUtf8("label_slic_sigma"))
        self.label_slic_sigma.setToolTip("width of the Gaussian kernel used in pre-smoothing before segmentation\nDefault = 100")
        self.horizontalLayout_12.addWidget(self.label_slic_sigma)
        self.spinBox_slic_sigma = QtGui.QSpinBox(self.layoutWidget_4)
        self.spinBox_slic_sigma.setMaximumSize(QtCore.QSize(55, 16777215))
        self.spinBox_slic_sigma.setMaximum(9999)
        self.spinBox_slic_sigma.setObjectName(_fromUtf8("spinBox_slic_sigma"))
        self.horizontalLayout_12.addWidget(self.spinBox_slic_sigma)
        self.layoutWidget_7 = QtGui.QWidget(self.frame_4)
        self.layoutWidget_7.setGeometry(QtCore.QRect(380, 50, 251, 63))
        self.layoutWidget_7.setObjectName(_fromUtf8("layoutWidget_7"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_segm_param_id = QtGui.QLabel(self.layoutWidget_7)
        self.label_segm_param_id.setObjectName(_fromUtf8("label_segm_param_id"))
        self.horizontalLayout_15.addWidget(self.label_segm_param_id)
        self.name_segm = QtGui.QLineEdit(self.layoutWidget_7)
        self.name_segm.setObjectName(_fromUtf8("name_segm"))
        self.horizontalLayout_15.addWidget(self.name_segm)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem1)
        self.save_segm = QtGui.QPushButton(self.layoutWidget_7)
        self.save_segm.setObjectName(_fromUtf8("save_segm"))
        self.horizontalLayout_16.addWidget(self.save_segm)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.layoutWidget_8 = QtGui.QWidget(self.frame_3)
        self.layoutWidget_8.setGeometry(QtCore.QRect(10, 30, 121, 102))
        self.layoutWidget_8.setObjectName(_fromUtf8("layoutWidget_8"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget_8)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_list_segm = QtGui.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_list_segm.setFont(font)
        self.label_list_segm.setTextFormat(QtCore.Qt.AutoText)
        self.label_list_segm.setObjectName(_fromUtf8("label_list_segm"))
        self.verticalLayout_6.addWidget(self.label_list_segm)
        self.list_segm = MyListWidget(self.layoutWidget_8)
        self.list_segm.setFrameShape(QtGui.QFrame.WinPanel)
        self.list_segm.setEditTriggers(QtGui.QAbstractItemView.EditKeyPressed)
        self.list_segm.setProperty("showDropIndicator", False)
        self.list_segm.setObjectName(_fromUtf8("list_segm"))
        self.verticalLayout_6.addWidget(self.list_segm)
        self.frame_5 = QtGui.QFrame(form)
        self.frame_5.setGeometry(QtCore.QRect(20, 390, 811, 161))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.frame_6 = QtGui.QFrame(self.frame_5)
        self.frame_6.setGeometry(QtCore.QRect(150, 20, 651, 131))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setLineWidth(28)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.layoutWidget_9 = QtGui.QWidget(self.frame_6)
        self.layoutWidget_9.setGeometry(QtCore.QRect(10, 10, 151, 26))
        self.layoutWidget_9.setObjectName(_fromUtf8("layoutWidget_9"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.layoutWidget_9)
        self.horizontalLayout_17.setMargin(0)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_n_texton = QtGui.QLabel(self.layoutWidget_9)
        self.label_n_texton.setObjectName(_fromUtf8("label_n_texton"))
        self.label_n_texton.setToolTip("number of texton, or the number of clusters\nwhen doing rotation-invariant k-means over Gabor responses\nDefault = 100")
        self.horizontalLayout_17.addWidget(self.label_n_texton)
        self.spinBox_n_texton = QtGui.QSpinBox(self.layoutWidget_9)
        self.spinBox_n_texton.setMaximumSize(QtCore.QSize(55, 16777215))
        self.spinBox_n_texton.setMaximum(9999)
        self.spinBox_n_texton.setObjectName(_fromUtf8("spinBox_n_texton"))
        self.horizontalLayout_17.addWidget(self.spinBox_n_texton)
        self.layoutWidget_10 = QtGui.QWidget(self.frame_6)
        self.layoutWidget_10.setGeometry(QtCore.QRect(10, 50, 151, 26))
        self.layoutWidget_10.setObjectName(_fromUtf8("layoutWidget_10"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.layoutWidget_10)
        self.horizontalLayout_18.setMargin(0)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_n_sample = QtGui.QLabel(self.layoutWidget_10)
        self.label_n_sample.setObjectName(_fromUtf8("label_n_sample"))
        self.label_n_sample.setToolTip("number of samples to use at each iteration of k-means\nDefault = 10,000")
        self.horizontalLayout_18.addWidget(self.label_n_sample)
        self.spinBox_n_sample = QtGui.QSpinBox(self.layoutWidget_10)
        self.spinBox_n_sample.setMaximumSize(QtCore.QSize(55, 16777215))
        self.spinBox_n_sample.setMaximum(9999)
        self.spinBox_n_sample.setObjectName(_fromUtf8("spinBox_n_sample"))
        self.horizontalLayout_18.addWidget(self.spinBox_n_sample)
        self.layoutWidget_11 = QtGui.QWidget(self.frame_6)
        self.layoutWidget_11.setGeometry(QtCore.QRect(10, 90, 151, 26))
        self.layoutWidget_11.setObjectName(_fromUtf8("layoutWidget_11"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.layoutWidget_11)
        self.horizontalLayout_19.setMargin(0)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_n_iter = QtGui.QLabel(self.layoutWidget_11)
        self.label_n_iter.setObjectName(_fromUtf8("label_n_iter"))
        self.label_n_iter.setToolTip("number of iterations of k-means\nDefault = 10")
        self.horizontalLayout_19.addWidget(self.label_n_iter)
        self.spinBox_n_iter = QtGui.QSpinBox(self.layoutWidget_11)
        self.spinBox_n_iter.setMaximumSize(QtCore.QSize(55, 16777215))
        self.spinBox_n_iter.setMaximum(9999)
        self.spinBox_n_iter.setObjectName(_fromUtf8("spinBox_n_iter"))
        self.horizontalLayout_19.addWidget(self.spinBox_n_iter)
        self.layoutWidget_14 = QtGui.QWidget(self.frame_6)
        self.layoutWidget_14.setGeometry(QtCore.QRect(380, 50, 251, 63))
        self.layoutWidget_14.setObjectName(_fromUtf8("layoutWidget_14"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget_14)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_vq_param_id = QtGui.QLabel(self.layoutWidget_14)
        self.label_vq_param_id.setObjectName(_fromUtf8("label_vq_param_id"))
        self.horizontalLayout_22.addWidget(self.label_vq_param_id)
        self.name_vq = QtGui.QLineEdit(self.layoutWidget_14)
        self.name_vq.setObjectName(_fromUtf8("name_vq"))
        self.horizontalLayout_22.addWidget(self.name_vq)
        self.verticalLayout_7.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem2)
        self.save_vq = QtGui.QPushButton(self.layoutWidget_14)
        self.save_vq.setObjectName(_fromUtf8("save_vq"))
        self.horizontalLayout_23.addWidget(self.save_vq)
        self.verticalLayout_7.addLayout(self.horizontalLayout_23)
        self.layoutWidget_15 = QtGui.QWidget(self.frame_5)
        self.layoutWidget_15.setGeometry(QtCore.QRect(10, 30, 121, 102))
        self.layoutWidget_15.setObjectName(_fromUtf8("layoutWidget_15"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.layoutWidget_15)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_list_vq = QtGui.QLabel(self.layoutWidget_15)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_list_vq.setFont(font)
        self.label_list_vq.setTextFormat(QtCore.Qt.AutoText)
        self.label_list_vq.setObjectName(_fromUtf8("label_list_vq"))
        self.verticalLayout_8.addWidget(self.label_list_vq)
        self.list_vq = MyListWidget(self.layoutWidget_15)
        self.list_vq.setFrameShape(QtGui.QFrame.WinPanel)
        self.list_vq.setProperty("showDropIndicator", False)
        self.list_vq.setObjectName(_fromUtf8("list_vq"))
        self.verticalLayout_8.addWidget(self.list_vq)

        self.retranslateUi(form)
        QtCore.QMetaObject.connectSlotsByName(form)

    def retranslateUi(self, form):
        form.setWindowTitle(_translate("form", "Parameter Set Settings", None))
        self.label_min_wavelen.setText(_translate("form", "min_wavelen", None))
        self.label_max_wavelen.setText(_translate("form", "max_wavelen", None))
        self.label_freq_step.setText(_translate("form", "freq_step", None))
        self.label_bandwidth.setText(_translate("form", "bandwidth", None))
        self.label_theta_interval.setText(_translate("form", "theta_interval", None))
        self.label_gabor_param_id.setText(_translate("form", "parameter_id", None))
        self.save_gabor.setText(_translate("form", "save", None))
        self.label_list_gabor.setText(_translate("form", "gabor", None))
        self.label_n_superpixels.setText(_translate("form", "n_superpixels", None))
        self.label_slic_compactness.setText(_translate("form", "slic_compactness", None))
        self.label_slic_sigma.setText(_translate("form", "slic_sigma", None))
        self.label_segm_param_id.setText(_translate("form", "parameter_id", None))
        self.save_segm.setText(_translate("form", "save", None))
        self.label_list_segm.setText(_translate("form", "segmentation", None))
        self.label_n_texton.setText(_translate("form", "n_texton", None))
        self.label_n_sample.setText(_translate("form", "n_sample", None))
        self.label_n_iter.setText(_translate("form", "n_iter", None))
        self.label_vq_param_id.setText(_translate("form", "parameter_id", None))
        self.save_vq.setText(_translate("form", "save", None))
        self.label_list_vq.setText(_translate("form", "vector quantization", None))

