# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MaskEditingGui3.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MaskEditingGui3(object):
    def setupUi(self, MaskEditingGui3):
        MaskEditingGui3.setObjectName(_fromUtf8("MaskEditingGui3"))
        MaskEditingGui3.resize(1046, 825)
        self.verticalLayout = QtGui.QVBoxLayout(MaskEditingGui3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.button_slic = QtGui.QPushButton(MaskEditingGui3)
        self.button_slic.setObjectName(_fromUtf8("button_slic"))
        self.gridLayout_2.addWidget(self.button_slic, 2, 2, 1, 1)
        self.label_3 = QtGui.QLabel(MaskEditingGui3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(MaskEditingGui3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.gview_dissimmap = QtGui.QGraphicsView(MaskEditingGui3)
        self.gview_dissimmap.setObjectName(_fromUtf8("gview_dissimmap"))
        self.gridLayout_2.addWidget(self.gview_dissimmap, 4, 0, 1, 1)
        self.gview_slic = QtGui.QGraphicsView(MaskEditingGui3)
        self.gview_slic.setMaximumSize(QtCore.QSize(500, 500))
        self.gview_slic.setObjectName(_fromUtf8("gview_slic"))
        self.gridLayout_2.addWidget(self.gview_slic, 1, 2, 1, 1)
        self.gview_thresholded = QtGui.QGraphicsView(MaskEditingGui3)
        self.gview_thresholded.setMaximumSize(QtCore.QSize(500, 500))
        self.gview_thresholded.setObjectName(_fromUtf8("gview_thresholded"))
        self.gridLayout_2.addWidget(self.gview_thresholded, 1, 1, 1, 1)
        self.gview_submasks = QtGui.QGraphicsView(MaskEditingGui3)
        self.gview_submasks.setObjectName(_fromUtf8("gview_submasks"))
        self.gridLayout_2.addWidget(self.gview_submasks, 4, 1, 1, 1)
        self.gview_finalMask = QtGui.QGraphicsView(MaskEditingGui3)
        self.gview_finalMask.setMaximumSize(QtCore.QSize(500, 500))
        self.gview_finalMask.setObjectName(_fromUtf8("gview_finalMask"))
        self.gridLayout_2.addWidget(self.gview_finalMask, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(MaskEditingGui3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_7 = QtGui.QLabel(MaskEditingGui3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(MaskEditingGui3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 2, 1, 1)
        self.gview_snake = QtGui.QGraphicsView(MaskEditingGui3)
        self.gview_snake.setObjectName(_fromUtf8("gview_snake"))
        self.gridLayout_2.addWidget(self.gview_snake, 4, 2, 1, 1)
        self.button_submasks = QtGui.QPushButton(MaskEditingGui3)
        self.button_submasks.setObjectName(_fromUtf8("button_submasks"))
        self.gridLayout_2.addWidget(self.button_submasks, 5, 1, 1, 1)
        self.label_9 = QtGui.QLabel(MaskEditingGui3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 3, 2, 1, 1)
        self.button_snake = QtGui.QPushButton(MaskEditingGui3)
        self.button_snake.setObjectName(_fromUtf8("button_snake"))
        self.gridLayout_2.addWidget(self.button_snake, 5, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.button_redoThisSection = QtGui.QPushButton(MaskEditingGui3)
        self.button_redoThisSection.setObjectName(_fromUtf8("button_redoThisSection"))
        self.gridLayout.addWidget(self.button_redoThisSection, 0, 2, 1, 1)
        self.button_confirmMasks = QtGui.QPushButton(MaskEditingGui3)
        self.button_confirmMasks.setObjectName(_fromUtf8("button_confirmMasks"))
        self.gridLayout.addWidget(self.button_confirmMasks, 4, 0, 1, 1)
        self.button_saveReview = QtGui.QPushButton(MaskEditingGui3)
        self.button_saveReview.setObjectName(_fromUtf8("button_saveReview"))
        self.gridLayout.addWidget(self.button_saveReview, 3, 2, 1, 1)
        self.button_uploadMasks = QtGui.QPushButton(MaskEditingGui3)
        self.button_uploadMasks.setObjectName(_fromUtf8("button_uploadMasks"))
        self.gridLayout.addWidget(self.button_uploadMasks, 4, 2, 1, 1)
        self.button_drawInitContour = QtGui.QPushButton(MaskEditingGui3)
        self.button_drawInitContour.setObjectName(_fromUtf8("button_drawInitContour"))
        self.gridLayout.addWidget(self.button_drawInitContour, 0, 0, 1, 1)
        self.button_loadReview = QtGui.QPushButton(MaskEditingGui3)
        self.button_loadReview.setObjectName(_fromUtf8("button_loadReview"))
        self.gridLayout.addWidget(self.button_loadReview, 3, 0, 1, 1)
        self.button_closeMaskGui = QtGui.QPushButton(MaskEditingGui3)
        self.button_closeMaskGui.setObjectName(_fromUtf8("button_closeMaskGui"))
        self.gridLayout.addWidget(self.button_closeMaskGui, 3, 4, 1, 1)
        self.label_2 = QtGui.QLabel(MaskEditingGui3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.comboBox_channel = QtGui.QComboBox(MaskEditingGui3)
        self.comboBox_channel.setObjectName(_fromUtf8("comboBox_channel"))
        self.gridLayout.addWidget(self.comboBox_channel, 0, 4, 1, 1)
        self.label_threshold = QtGui.QLabel(MaskEditingGui3)
        self.label_threshold.setObjectName(_fromUtf8("label_threshold"))
        self.gridLayout.addWidget(self.label_threshold, 1, 3, 1, 1)
        self.slider_threshold = QtGui.QSlider(MaskEditingGui3)
        self.slider_threshold.setOrientation(QtCore.Qt.Horizontal)
        self.slider_threshold.setObjectName(_fromUtf8("slider_threshold"))
        self.gridLayout.addWidget(self.slider_threshold, 1, 2, 1, 1)
        self.label = QtGui.QLabel(MaskEditingGui3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.slider_dissimThresh = QtGui.QSlider(MaskEditingGui3)
        self.slider_dissimThresh.setOrientation(QtCore.Qt.Horizontal)
        self.slider_dissimThresh.setObjectName(_fromUtf8("slider_dissimThresh"))
        self.gridLayout.addWidget(self.slider_dissimThresh, 2, 2, 1, 1)
        self.label_8 = QtGui.QLabel(MaskEditingGui3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_dissimThresh = QtGui.QLabel(MaskEditingGui3)
        self.label_dissimThresh.setObjectName(_fromUtf8("label_dissimThresh"))
        self.gridLayout.addWidget(self.label_dissimThresh, 2, 3, 1, 1)
        self.button_confirmDissimThresh = QtGui.QPushButton(MaskEditingGui3)
        self.button_confirmDissimThresh.setObjectName(_fromUtf8("button_confirmDissimThresh"))
        self.gridLayout.addWidget(self.button_confirmDissimThresh, 2, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(MaskEditingGui3)
        QtCore.QMetaObject.connectSlotsByName(MaskEditingGui3)

    def retranslateUi(self, MaskEditingGui3):
        MaskEditingGui3.setWindowTitle(_translate("MaskEditingGui3", "Review Masks", None))
        self.button_slic.setText(_translate("MaskEditingGui3", "Update", None))
        self.label_3.setText(_translate("MaskEditingGui3", "Original", None))
        self.label_4.setText(_translate("MaskEditingGui3", "Thresholded", None))
        self.label_6.setText(_translate("MaskEditingGui3", "Foreground Map", None))
        self.label_7.setText(_translate("MaskEditingGui3", "Submasks", None))
        self.label_5.setText(_translate("MaskEditingGui3", "SLIC", None))
        self.button_submasks.setText(_translate("MaskEditingGui3", "Update", None))
        self.label_9.setText(_translate("MaskEditingGui3", "Snake", None))
        self.button_snake.setText(_translate("MaskEditingGui3", "Update", None))
        self.button_redoThisSection.setText(_translate("MaskEditingGui3", "Redo this Section", None))
        self.button_confirmMasks.setText(_translate("MaskEditingGui3", "Confirm", None))
        self.button_saveReview.setText(_translate("MaskEditingGui3", "Save Review", None))
        self.button_uploadMasks.setText(_translate("MaskEditingGui3", "Upload", None))
        self.button_drawInitContour.setText(_translate("MaskEditingGui3", "Draw Initial Contour", None))
        self.button_loadReview.setText(_translate("MaskEditingGui3", "Load Review", None))
        self.button_closeMaskGui.setText(_translate("MaskEditingGui3", "Close", None))
        self.label_2.setText(_translate("MaskEditingGui3", "Channel", None))
        self.label_threshold.setText(_translate("MaskEditingGui3", "200", None))
        self.label.setText(_translate("MaskEditingGui3", "Threshold", None))
        self.label_8.setText(_translate("MaskEditingGui3", "Dissim Threshold", None))
        self.label_dissimThresh.setText(_translate("MaskEditingGui3", "0.5", None))
        self.button_confirmDissimThresh.setText(_translate("MaskEditingGui3", "Confirm", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MaskEditingGui3 = QtGui.QDialog()
    ui = Ui_MaskEditingGui3()
    ui.setupUi(MaskEditingGui3)
    MaskEditingGui3.show()
    sys.exit(app.exec_())

