# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BrainLabelingGui_v10.ui'
#
# Created: Thu Nov 12 18:28:50 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BrainLabelingGui(object):
    def setupUi(self, BrainLabelingGui):
        BrainLabelingGui.setObjectName(_fromUtf8("BrainLabelingGui"))
        BrainLabelingGui.resize(1040, 915)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BrainLabelingGui.sizePolicy().hasHeightForWidth())
        BrainLabelingGui.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(BrainLabelingGui)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.thumbnail_list = QtGui.QListWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thumbnail_list.sizePolicy().hasHeightForWidth())
        self.thumbnail_list.setSizePolicy(sizePolicy)
        self.thumbnail_list.setMinimumSize(QtCore.QSize(256, 773))
        self.thumbnail_list.setObjectName(_fromUtf8("thumbnail_list"))
        self.widget = QtGui.QWidget(self.splitter)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.canvaswidget = MplWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvaswidget.sizePolicy().hasHeightForWidth())
        self.canvaswidget.setSizePolicy(sizePolicy)
        self.canvaswidget.setMinimumSize(QtCore.QSize(761, 571))
        self.canvaswidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.canvaswidget.setObjectName(_fromUtf8("canvaswidget"))
        self.verticalLayout_4.addWidget(self.canvaswidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.proposalSource_panel = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.proposalSource_panel.sizePolicy().hasHeightForWidth())
        self.proposalSource_panel.setSizePolicy(sizePolicy)
        self.proposalSource_panel.setFlat(False)
        self.proposalSource_panel.setObjectName(_fromUtf8("proposalSource_panel"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.proposalSource_panel)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.radioButton_globalProposal = QtGui.QRadioButton(self.proposalSource_panel)
        self.radioButton_globalProposal.setObjectName(_fromUtf8("radioButton_globalProposal"))
        self.verticalLayout_2.addWidget(self.radioButton_globalProposal)
        self.radioButton_localProposal = QtGui.QRadioButton(self.proposalSource_panel)
        self.radioButton_localProposal.setObjectName(_fromUtf8("radioButton_localProposal"))
        self.verticalLayout_2.addWidget(self.radioButton_localProposal)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.proposalSource_panel)
        self.displayOption_panel = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayOption_panel.sizePolicy().hasHeightForWidth())
        self.displayOption_panel.setSizePolicy(sizePolicy)
        self.displayOption_panel.setObjectName(_fromUtf8("displayOption_panel"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.displayOption_panel)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.img_radioButton = QtGui.QRadioButton(self.displayOption_panel)
        self.img_radioButton.setObjectName(_fromUtf8("img_radioButton"))
        self.verticalLayout_3.addWidget(self.img_radioButton)
        self.textonmap_radioButton = QtGui.QRadioButton(self.displayOption_panel)
        self.textonmap_radioButton.setObjectName(_fromUtf8("textonmap_radioButton"))
        self.verticalLayout_3.addWidget(self.textonmap_radioButton)
        self.dirmap_radioButton = QtGui.QRadioButton(self.displayOption_panel)
        self.dirmap_radioButton.setObjectName(_fromUtf8("dirmap_radioButton"))
        self.verticalLayout_3.addWidget(self.dirmap_radioButton)
        self.buttonSpOnOff = QtGui.QPushButton(self.displayOption_panel)
        self.buttonSpOnOff.setObjectName(_fromUtf8("buttonSpOnOff"))
        self.verticalLayout_3.addWidget(self.buttonSpOnOff)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout.addWidget(self.displayOption_panel)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.spinBox_section = QtGui.QSpinBox(self.widget)
        self.spinBox_section.setKeyboardTracking(False)
        self.spinBox_section.setMaximum(300)
        self.spinBox_section.setObjectName(_fromUtf8("spinBox_section"))
        self.horizontalLayout_2.addWidget(self.spinBox_section)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.button_autoDetect = QtGui.QPushButton(self.widget)
        self.button_autoDetect.setObjectName(_fromUtf8("button_autoDetect"))
        self.verticalLayout.addWidget(self.button_autoDetect)
        self.button_updateDB = QtGui.QPushButton(self.widget)
        self.button_updateDB.setObjectName(_fromUtf8("button_updateDB"))
        self.verticalLayout.addWidget(self.button_updateDB)
        self.button_loadLabeling = QtGui.QPushButton(self.widget)
        self.button_loadLabeling.setObjectName(_fromUtf8("button_loadLabeling"))
        self.verticalLayout.addWidget(self.button_loadLabeling)
        self.button_saveLabeling = QtGui.QPushButton(self.widget)
        self.button_saveLabeling.setObjectName(_fromUtf8("button_saveLabeling"))
        self.verticalLayout.addWidget(self.button_saveLabeling)
        self.button_quit = QtGui.QPushButton(self.widget)
        self.button_quit.setObjectName(_fromUtf8("button_quit"))
        self.verticalLayout.addWidget(self.button_quit)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        BrainLabelingGui.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(BrainLabelingGui)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        BrainLabelingGui.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(BrainLabelingGui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1040, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        BrainLabelingGui.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(BrainLabelingGui)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        BrainLabelingGui.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar.addSeparator()

        self.retranslateUi(BrainLabelingGui)
        QtCore.QMetaObject.connectSlotsByName(BrainLabelingGui)

    def retranslateUi(self, BrainLabelingGui):
        BrainLabelingGui.setWindowTitle(_translate("BrainLabelingGui", "BrainLabelingGui", None))
        self.proposalSource_panel.setTitle(_translate("BrainLabelingGui", "Proposal Source", None))
        self.radioButton_globalProposal.setText(_translate("BrainLabelingGui", "Global Proposals", None))
        self.radioButton_localProposal.setText(_translate("BrainLabelingGui", "Local Proposals", None))
        self.displayOption_panel.setTitle(_translate("BrainLabelingGui", "Display", None))
        self.img_radioButton.setText(_translate("BrainLabelingGui", "image", None))
        self.textonmap_radioButton.setText(_translate("BrainLabelingGui", "textonmap", None))
        self.dirmap_radioButton.setText(_translate("BrainLabelingGui", "directionality", None))
        self.buttonSpOnOff.setText(_translate("BrainLabelingGui", "Turn Superpixels On", None))
        self.label.setText(_translate("BrainLabelingGui", "section #", None))
        self.button_autoDetect.setText(_translate("BrainLabelingGui", "Auto Detect", None))
        self.button_updateDB.setText(_translate("BrainLabelingGui", "Update DB", None))
        self.button_loadLabeling.setText(_translate("BrainLabelingGui", "Load", None))
        self.button_saveLabeling.setText(_translate("BrainLabelingGui", "Save", None))
        self.button_quit.setText(_translate("BrainLabelingGui", "Quit", None))
        self.toolBar.setWindowTitle(_translate("BrainLabelingGui", "toolBar", None))

from mplwidget import MplWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    BrainLabelingGui = QtGui.QMainWindow()
    ui = Ui_BrainLabelingGui()
    ui.setupUi(BrainLabelingGui)
    BrainLabelingGui.show()
    sys.exit(app.exec_())

