# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BrainLabelingGui_v11.ui'
#
# Created: Tue Dec 29 15:10:56 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BrainLabelingGui(object):
    def setupUi(self, BrainLabelingGui):
        BrainLabelingGui.setObjectName(_fromUtf8("BrainLabelingGui"))
        BrainLabelingGui.resize(1298, 915)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BrainLabelingGui.sizePolicy().hasHeightForWidth())
        BrainLabelingGui.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(BrainLabelingGui)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.thumbnail_list = QtGui.QListWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thumbnail_list.sizePolicy().hasHeightForWidth())
        self.thumbnail_list.setSizePolicy(sizePolicy)
        self.thumbnail_list.setMinimumSize(QtCore.QSize(256, 773))
        self.thumbnail_list.setObjectName(_fromUtf8("thumbnail_list"))
        self.gridLayout.addWidget(self.thumbnail_list, 0, 0, 3, 1)
        self.bottom_panel = QtGui.QHBoxLayout()
        self.bottom_panel.setObjectName(_fromUtf8("bottom_panel"))
        self.graphicsView_navMap = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView_navMap.setObjectName(_fromUtf8("graphicsView_navMap"))
        self.bottom_panel.addWidget(self.graphicsView_navMap)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.bottom_panel.addItem(spacerItem)
        self.proposalSource_panel = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.proposalSource_panel.sizePolicy().hasHeightForWidth())
        self.proposalSource_panel.setSizePolicy(sizePolicy)
        self.proposalSource_panel.setFlat(False)
        self.proposalSource_panel.setObjectName(_fromUtf8("proposalSource_panel"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.proposalSource_panel)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.radioButton_globalProposal = QtGui.QRadioButton(self.proposalSource_panel)
        self.radioButton_globalProposal.setObjectName(_fromUtf8("radioButton_globalProposal"))
        self.verticalLayout_2.addWidget(self.radioButton_globalProposal)
        self.radioButton_localProposal = QtGui.QRadioButton(self.proposalSource_panel)
        self.radioButton_localProposal.setObjectName(_fromUtf8("radioButton_localProposal"))
        self.verticalLayout_2.addWidget(self.radioButton_localProposal)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.bottom_panel.addWidget(self.proposalSource_panel)
        self.displayOption_panel = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayOption_panel.sizePolicy().hasHeightForWidth())
        self.displayOption_panel.setSizePolicy(sizePolicy)
        self.displayOption_panel.setObjectName(_fromUtf8("displayOption_panel"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.displayOption_panel)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.img_radioButton = QtGui.QRadioButton(self.displayOption_panel)
        self.img_radioButton.setObjectName(_fromUtf8("img_radioButton"))
        self.verticalLayout_3.addWidget(self.img_radioButton)
        self.textonmap_radioButton = QtGui.QRadioButton(self.displayOption_panel)
        self.textonmap_radioButton.setObjectName(_fromUtf8("textonmap_radioButton"))
        self.verticalLayout_3.addWidget(self.textonmap_radioButton)
        self.dirmap_radioButton = QtGui.QRadioButton(self.displayOption_panel)
        self.dirmap_radioButton.setObjectName(_fromUtf8("dirmap_radioButton"))
        self.verticalLayout_3.addWidget(self.dirmap_radioButton)
        self.buttonSpOnOff = QtGui.QPushButton(self.displayOption_panel)
        self.buttonSpOnOff.setObjectName(_fromUtf8("buttonSpOnOff"))
        self.verticalLayout_3.addWidget(self.buttonSpOnOff)
        self.button_labelsOnOff = QtGui.QPushButton(self.displayOption_panel)
        self.button_labelsOnOff.setObjectName(_fromUtf8("button_labelsOnOff"))
        self.verticalLayout_3.addWidget(self.button_labelsOnOff)
        self.button_contoursOnOff = QtGui.QPushButton(self.displayOption_panel)
        self.button_contoursOnOff.setObjectName(_fromUtf8("button_contoursOnOff"))
        self.verticalLayout_3.addWidget(self.button_contoursOnOff)
        self.button_verticesOnOff = QtGui.QPushButton(self.displayOption_panel)
        self.button_verticesOnOff.setObjectName(_fromUtf8("button_verticesOnOff"))
        self.verticalLayout_3.addWidget(self.button_verticesOnOff)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.bottom_panel.addWidget(self.displayOption_panel)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.button_autoDetect = QtGui.QPushButton(self.centralwidget)
        self.button_autoDetect.setObjectName(_fromUtf8("button_autoDetect"))
        self.verticalLayout.addWidget(self.button_autoDetect)
        self.button_updateDB = QtGui.QPushButton(self.centralwidget)
        self.button_updateDB.setObjectName(_fromUtf8("button_updateDB"))
        self.verticalLayout.addWidget(self.button_updateDB)
        self.button_loadLabeling = QtGui.QPushButton(self.centralwidget)
        self.button_loadLabeling.setObjectName(_fromUtf8("button_loadLabeling"))
        self.verticalLayout.addWidget(self.button_loadLabeling)
        self.button_saveLabeling = QtGui.QPushButton(self.centralwidget)
        self.button_saveLabeling.setObjectName(_fromUtf8("button_saveLabeling"))
        self.verticalLayout.addWidget(self.button_saveLabeling)
        self.button_quit = QtGui.QPushButton(self.centralwidget)
        self.button_quit.setObjectName(_fromUtf8("button_quit"))
        self.verticalLayout.addWidget(self.button_quit)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.bottom_panel.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.bottom_panel, 2, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.button_loadLabelingSec3 = QtGui.QPushButton(self.centralwidget)
        self.button_loadLabelingSec3.setObjectName(_fromUtf8("button_loadLabelingSec3"))
        self.horizontalLayout.addWidget(self.button_loadLabelingSec3)
        self.button_loadLabelingSec1 = QtGui.QPushButton(self.centralwidget)
        self.button_loadLabelingSec1.setObjectName(_fromUtf8("button_loadLabelingSec1"))
        self.horizontalLayout.addWidget(self.button_loadLabelingSec1)
        self.button_loadLabelingSec2 = QtGui.QPushButton(self.centralwidget)
        self.button_loadLabelingSec2.setObjectName(_fromUtf8("button_loadLabelingSec2"))
        self.horizontalLayout.addWidget(self.button_loadLabelingSec2)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.section3_gview = QtGui.QGraphicsView(self.splitter)
        self.section3_gview.setMinimumSize(QtCore.QSize(333, 1000))
        self.section3_gview.setObjectName(_fromUtf8("section3_gview"))
        self.section1_gview = QtGui.QGraphicsView(self.splitter)
        self.section1_gview.setMinimumSize(QtCore.QSize(333, 1000))
        self.section1_gview.setObjectName(_fromUtf8("section1_gview"))
        self.section2_gview = QtGui.QGraphicsView(self.splitter)
        self.section2_gview.setMinimumSize(QtCore.QSize(333, 1000))
        self.section2_gview.setObjectName(_fromUtf8("section2_gview"))
        self.gridLayout.addWidget(self.splitter, 0, 1, 1, 1)
        BrainLabelingGui.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(BrainLabelingGui)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        BrainLabelingGui.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(BrainLabelingGui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1298, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        BrainLabelingGui.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(BrainLabelingGui)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        BrainLabelingGui.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar.addSeparator()

        self.retranslateUi(BrainLabelingGui)
        QtCore.QMetaObject.connectSlotsByName(BrainLabelingGui)

    def retranslateUi(self, BrainLabelingGui):
        BrainLabelingGui.setWindowTitle(_translate("BrainLabelingGui", "BrainLabelingGui", None))
        self.proposalSource_panel.setTitle(_translate("BrainLabelingGui", "Proposal Source", None))
        self.radioButton_globalProposal.setText(_translate("BrainLabelingGui", "Global Proposals", None))
        self.radioButton_localProposal.setText(_translate("BrainLabelingGui", "Local Proposals", None))
        self.displayOption_panel.setTitle(_translate("BrainLabelingGui", "Display", None))
        self.img_radioButton.setText(_translate("BrainLabelingGui", "image", None))
        self.textonmap_radioButton.setText(_translate("BrainLabelingGui", "textonmap", None))
        self.dirmap_radioButton.setText(_translate("BrainLabelingGui", "directionality", None))
        self.buttonSpOnOff.setText(_translate("BrainLabelingGui", "Turn Superpixels On", None))
        self.button_labelsOnOff.setText(_translate("BrainLabelingGui", "Turn Labels Off", None))
        self.button_contoursOnOff.setText(_translate("BrainLabelingGui", "Turn Contours Off", None))
        self.button_verticesOnOff.setText(_translate("BrainLabelingGui", "Turn Vertices Off", None))
        self.button_autoDetect.setText(_translate("BrainLabelingGui", "Auto Detect", None))
        self.button_updateDB.setText(_translate("BrainLabelingGui", "Update DB", None))
        self.button_loadLabeling.setText(_translate("BrainLabelingGui", "Load", None))
        self.button_saveLabeling.setText(_translate("BrainLabelingGui", "Save", None))
        self.button_quit.setText(_translate("BrainLabelingGui", "Quit", None))
        self.button_loadLabelingSec3.setText(_translate("BrainLabelingGui", "Load", None))
        self.button_loadLabelingSec1.setText(_translate("BrainLabelingGui", "Load", None))
        self.button_loadLabelingSec2.setText(_translate("BrainLabelingGui", "Load", None))
        self.toolBar.setWindowTitle(_translate("BrainLabelingGui", "toolBar", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    BrainLabelingGui = QtGui.QMainWindow()
    ui = Ui_BrainLabelingGui()
    ui.setupUi(BrainLabelingGui)
    BrainLabelingGui.show()
    sys.exit(app.exec_())

