# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MaskEditingGui5.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MaskEditingGui(object):
    def setupUi(self, MaskEditingGui):
        MaskEditingGui.setObjectName(_fromUtf8("MaskEditingGui"))
        MaskEditingGui.resize(1046, 825)
        self.gridLayout = QtGui.QGridLayout(MaskEditingGui)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_3 = QtGui.QLabel(MaskEditingGui)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.init_snake_contour_gview = QtGui.QGraphicsView(MaskEditingGui)
        self.init_snake_contour_gview.setMaximumSize(QtCore.QSize(800, 500))
        self.init_snake_contour_gview.setObjectName(_fromUtf8("init_snake_contour_gview"))
        self.verticalLayout.addWidget(self.init_snake_contour_gview)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(MaskEditingGui)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.pushButton = QtGui.QPushButton(MaskEditingGui)
        self.pushButton.setText(_fromUtf8(""))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_4 = QtGui.QLabel(MaskEditingGui)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.gview_thresholded = QtGui.QGraphicsView(MaskEditingGui)
        self.gview_thresholded.setMaximumSize(QtCore.QSize(800, 500))
        self.gview_thresholded.setObjectName(_fromUtf8("gview_thresholded"))
        self.verticalLayout_2.addWidget(self.gview_thresholded)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(MaskEditingGui)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.comboBox_channel = QtGui.QComboBox(MaskEditingGui)
        self.comboBox_channel.setObjectName(_fromUtf8("comboBox_channel"))
        self.horizontalLayout_3.addWidget(self.comboBox_channel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_9 = QtGui.QLabel(MaskEditingGui)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_3.addWidget(self.label_9)
        self.gview_final_masks_user = QtGui.QGraphicsView(MaskEditingGui)
        self.gview_final_masks_user.setMaximumSize(QtCore.QSize(800, 500))
        self.gview_final_masks_user.setObjectName(_fromUtf8("gview_final_masks_user"))
        self.verticalLayout_3.addWidget(self.gview_final_masks_user)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(MaskEditingGui)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.slider_snakeShrink = QtGui.QSlider(MaskEditingGui)
        self.slider_snakeShrink.setOrientation(QtCore.Qt.Horizontal)
        self.slider_snakeShrink.setObjectName(_fromUtf8("slider_snakeShrink"))
        self.horizontalLayout_4.addWidget(self.slider_snakeShrink)
        self.label_snakeShrink = QtGui.QLabel(MaskEditingGui)
        self.label_snakeShrink.setObjectName(_fromUtf8("label_snakeShrink"))
        self.horizontalLayout_4.addWidget(self.label_snakeShrink)
        self.label_7 = QtGui.QLabel(MaskEditingGui)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_4.addWidget(self.label_7)
        self.slider_minSize = QtGui.QSlider(MaskEditingGui)
        self.slider_minSize.setOrientation(QtCore.Qt.Horizontal)
        self.slider_minSize.setObjectName(_fromUtf8("slider_minSize"))
        self.horizontalLayout_4.addWidget(self.slider_minSize)
        self.label_minSize = QtGui.QLabel(MaskEditingGui)
        self.label_minSize.setObjectName(_fromUtf8("label_minSize"))
        self.horizontalLayout_4.addWidget(self.label_minSize)
        self.button_snake = QtGui.QPushButton(MaskEditingGui)
        self.button_snake.setObjectName(_fromUtf8("button_snake"))
        self.horizontalLayout_4.addWidget(self.button_snake)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_6 = QtGui.QLabel(MaskEditingGui)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_4.addWidget(self.label_6)
        self.gview_merged_mask = QtGui.QGraphicsView(MaskEditingGui)
        self.gview_merged_mask.setMaximumSize(QtCore.QSize(800, 500))
        self.gview_merged_mask.setObjectName(_fromUtf8("gview_merged_mask"))
        self.verticalLayout_4.addWidget(self.gview_merged_mask)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.button_update_merged_mask = QtGui.QPushButton(MaskEditingGui)
        self.button_update_merged_mask.setObjectName(_fromUtf8("button_update_merged_mask"))
        self.horizontalLayout_2.addWidget(self.button_update_merged_mask)
        self.button_toggle_accept_auto = QtGui.QPushButton(MaskEditingGui)
        self.button_toggle_accept_auto.setText(_fromUtf8(""))
        self.button_toggle_accept_auto.setObjectName(_fromUtf8("button_toggle_accept_auto"))
        self.horizontalLayout_2.addWidget(self.button_toggle_accept_auto)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 1, 1, 1)
        self.line = QtGui.QFrame(MaskEditingGui)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 2, 0, 1, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.button_autoSnake = QtGui.QPushButton(MaskEditingGui)
        self.button_autoSnake.setObjectName(_fromUtf8("button_autoSnake"))
        self.horizontalLayout.addWidget(self.button_autoSnake)
        self.button_loadAnchorContours = QtGui.QPushButton(MaskEditingGui)
        self.button_loadAnchorContours.setObjectName(_fromUtf8("button_loadAnchorContours"))
        self.horizontalLayout.addWidget(self.button_loadAnchorContours)
        self.button_saveAnchorContours = QtGui.QPushButton(MaskEditingGui)
        self.button_saveAnchorContours.setObjectName(_fromUtf8("button_saveAnchorContours"))
        self.horizontalLayout.addWidget(self.button_saveAnchorContours)
        self.button_loadAllInitContours = QtGui.QPushButton(MaskEditingGui)
        self.button_loadAllInitContours.setObjectName(_fromUtf8("button_loadAllInitContours"))
        self.horizontalLayout.addWidget(self.button_loadAllInitContours)
        self.button_saveAllInitContours = QtGui.QPushButton(MaskEditingGui)
        self.button_saveAllInitContours.setObjectName(_fromUtf8("button_saveAllInitContours"))
        self.horizontalLayout.addWidget(self.button_saveAllInitContours)
        self.button_saveFinalMasks = QtGui.QPushButton(MaskEditingGui)
        self.button_saveFinalMasks.setObjectName(_fromUtf8("button_saveFinalMasks"))
        self.horizontalLayout.addWidget(self.button_saveFinalMasks)
        self.button_uploadMasks = QtGui.QPushButton(MaskEditingGui)
        self.button_uploadMasks.setObjectName(_fromUtf8("button_uploadMasks"))
        self.horizontalLayout.addWidget(self.button_uploadMasks)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 2)

        self.retranslateUi(MaskEditingGui)
        QtCore.QMetaObject.connectSlotsByName(MaskEditingGui)

    def retranslateUi(self, MaskEditingGui):
        MaskEditingGui.setWindowTitle(_translate("MaskEditingGui", "Review Masks", None))
        self.label_3.setText(_translate("MaskEditingGui", "Initial Submask Contour", None))
        self.label_5.setText(_translate("MaskEditingGui", "TextLabel", None))
        self.label_4.setText(_translate("MaskEditingGui", "Contrast Enhanced Image", None))
        self.label_2.setText(_translate("MaskEditingGui", "Channel", None))
        self.label_9.setText(_translate("MaskEditingGui", "Submasks", None))
        self.label.setText(_translate("MaskEditingGui", "Shrink", None))
        self.label_snakeShrink.setText(_translate("MaskEditingGui", "TextLabel", None))
        self.label_7.setText(_translate("MaskEditingGui", "Min Size", None))
        self.label_minSize.setText(_translate("MaskEditingGui", "TextLabel", None))
        self.button_snake.setText(_translate("MaskEditingGui", "Do Snake", None))
        self.label_6.setText(_translate("MaskEditingGui", "Merged Mask", None))
        self.button_update_merged_mask.setText(_translate("MaskEditingGui", "Update Merged Mask", None))
        self.button_autoSnake.setText(_translate("MaskEditingGui", "Automatically Generate Masks for All", None))
        self.button_loadAnchorContours.setText(_translate("MaskEditingGui", "Load Anchor Contours", None))
        self.button_saveAnchorContours.setText(_translate("MaskEditingGui", "Save Anchor Contours", None))
        self.button_loadAllInitContours.setText(_translate("MaskEditingGui", "Load All Init Contours", None))
        self.button_saveAllInitContours.setText(_translate("MaskEditingGui", "Save All Init Contours", None))
        self.button_saveFinalMasks.setText(_translate("MaskEditingGui", "Save Final Masks", None))
        self.button_uploadMasks.setText(_translate("MaskEditingGui", "Upload", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MaskEditingGui = QtGui.QDialog()
    ui = Ui_MaskEditingGui()
    ui.setupUi(MaskEditingGui)
    MaskEditingGui.show()
    sys.exit(app.exec_())

